# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: The Oxford Voice
masthead_title: "The Oxford Voice"
subtitle: Community news for Oxford, UK
email: editorial@theoxfordvoice.com
description: >- # this means to ignore newlines until "baseurl:"
  The Oxford Voice offers community news for Oxford, UK
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://theoxfordvoice.com" # the base hostname & protocol for your site, e.g. http://example.com

# twitter_username: jekyllrb
# github_username:  jekyll

# head_scripts:
#  - https://code.jquery.com/jquery-3.2.1.min.js
#  - /assets/js/your-custom-head-script.js

# Build settings
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
repository: example.github.io

# https://mmistakes.github.io/minimal-mistakes/docs/configuration/

minimal_mistakes_skin: "contrast" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"

markdown: kramdown

locale: "en-GB"
name: Oxford Voice
logo: "/assets/images/logo-100.png"
# teaser: /assets/images/default-teaser.jpg

# Outputting
permalink: /:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/

include: ["_pages"]

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true  
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      show_date: true

search: true
      
comments:
  provider: "facebook"
  facebook:
    appid: # optional
    num_posts: # 5 (default)
    colorscheme: # "light" (default), "dark"      
    